[project]
name = "hw-genie-workspace"
version = "0.1.0"
description = "Hero Wars Genie Workspace"
authors = [{ name = "JoichiroAkimoto" }]
requires-python = ">=3.10, <3.14"
dependencies = [
    "hw-genie",
]

[tool.uv]
managed = true
package = false

[tool.uv.workspace]
members = ["src/python"]

[tool.uv.sources]
hw-genie = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=9.0.2,<9.2.0",
    "pytest-mock~=3.15.1",
    "pytest-cov>=6.1,<7.2",
    "ruff~=0.15.10",
]
ci = [
    "google-genai",
    "unidiff>=0.7.5",
]
